/*
 *  UCF COP3330 Fall 2021 Assignment 3 Solutions
 *  Copyright 2021 Joshua Davis
 */

package baseline;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PasswordGeneratorTest{
    // Instantiate new PasswordGenerator object.
    PasswordGenerator passwordGeneratorTest = new PasswordGenerator();

    @Test
    void randomNumberGenerator(){
        // Test that a random number in a given range is generated by running 1000 tests.
        for(int i=0;i<1000;i++){
            assertTrue(passwordGeneratorTest.randomNumberGenerator(1, 10)<=10 && passwordGeneratorTest.randomNumberGenerator(1, 10)>=1);
        }
    }

    @Test
    void passwordConstructor(){
        // Test that a password constructs correctly using simulated passed values.
        boolean flag = false;
        int numCount=0;
        int letterCount=0;
        int specialCount=0;
        String passwordTest = passwordGeneratorTest.passwordConstructor(2, 4, 2, 8);
        assertEquals(8, passwordTest.length());
        assertNotEquals("Error.", passwordTest);
        for(int i=0;i<passwordTest.length();i++){
            if(passwordTest.charAt(i) >= 'a' && passwordTest.charAt(i) <= 'z') letterCount++;
            else if(passwordTest.charAt(i) >= '0' && passwordTest.charAt(i) <= '9') numCount++;
            else specialCount++;
        }
        assertEquals(8, letterCount + numCount + specialCount);
        assertEquals(4, letterCount);
        assertEquals(2, numCount);
        assertEquals(2, specialCount);
    }
}